name: Publish VPAT
description: Publish the most product recent VPAT to the docs site
author: Deque Systems, Inc.

inputs:
  docs-site-github-token:
    description: GitHub token to access the docs-site repository
    required: true
  docs-site-repository:
    description: GitHub repository containing the docs-site
    required: true
  product-name:
    description: Human-readable product name
    required: true
  product-id:
    description: Brief token that identifies your product - should match product id in docs site
    required: true
  vpat-location:
    description: Path to directory containing VPATs
    default: vpats

runs:
  using: composite
  steps:
    - name: Set action-wide environment variables
      id: constants
      shell: bash
      run: |
        echo "DOCS_SITE_BASE_BRANCH=develop" >> $GITHUB_ENV
        echo "DOCS_SITE_HEAD_BRANCH=publish-vpat-${{ inputs.product-id }}" >> $GITHUB_ENV
        echo "GH_TOKEN=${{ inputs.docs-site-github-token }}" >> $GITHUB_ENV

    - name: Configure node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Checkout action
      uses: actions/checkout@v3

    - name: Convert most recent VPAT to HTML
      uses: ./.github/actions/vpat-to-html
      with:
        product-name: ${{ inputs.product-name }}
        vpat-location: ${{ inputs.vpat-location }}

    - name: Clone docs-site repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.docs-site-repository }}
        token: ${{ inputs.docs-site-github-token }}
        path: docs-site
        fetch-depth: 0

    - name: Commit changes and create a pull request
      shell: bash
      working-directory: docs-site
      run: |
        echo "Commit changes and create a pull request"

        echo "Checkout base branch"
        git checkout -b "$DOCS_SITE_HEAD_BRANCH"
        git pull origin "$DOCS_SITE_HEAD_BRANCH" || true

        echo "Copying VPAT file to docs-site directory"
        source_file="../vpat.html"
        destination_dir="docs-site/static/vpats/${{ inputs.product-id }}"
        if [ ! -d "$destination_dir" ]; then
          echo "Creating directory: $destination_dir"
          mkdir -p "$destination_dir"
        fi
        cp "$source_file" "$destination_dir/"
        echo "VPAT copied to $destination_dir"

        echo "Checking for changes to commit"
        if ! [ git diff --quiet ]; then

          echo "Committing changes to feature branch"
          git config user.name "deque-docs"
          git config user.email "deque-docs@github.com"
          git add .
          git commit -m "chore: update VPAT for ${{ inputs.product-id }}"
          git push origin "$DOCS_SITE_HEAD_BRANCH"

          echo "Creating pull request"
          gh pr create \
            --repo ${{ inputs.docs-site-repository }} \
            --head $DOCS_SITE_HEAD_BRANCH \
            --base ${{ inputs.docs-site-base-branch }} \
            --title "Update VPAT for ${{ inputs.product-name }}" \
            --body "This PR was automatically generated by [action-vpat-upload](https://github.com/dequelabs/action-vpat-upload)" \
            --reviewer isner
        else
          echo "No changes to commit"
        fi
