name: Test

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Get the test vpat files
      - uses: actions/checkout@v3

      - uses: ./
        with:
          docs-site-github-token: ${{ secrets.DOCS_SITE_GITHUB_TOKEN }}
          product-name: 'Test Product'
          product-id: 'test'
          vpat-location: 'test/vpats'
