name: Test

on: push

jobs:
  # If successful, test.html will be uploaded to the bucket
  # and will contain "(Created Last)" in the product name.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: 'deque-vpats'
          product-name: 'Test Product'
          product-id: 'test'
          vpat-location: 'test/vpats'
